### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by friedger** [web3devs/stacks-bitcoin-api#5]
The first sentence should something like:
"stacks-bitcoin-api is a web library to easily verify BTC transactions on Stacks"

In Background:
* Remove or clarify `This project allow smart contract developers to verify transactions which occured on the Bitcoin blockchain.`

In How it works:
* Replace `Once a proof is assembled, the entirety of the proof is sent to a Clarity smart contract endpoint. The smart contract is responsible for forwarding the proof to the clarity-bitcoin.clar contract for confirmation of its validity.` with something like Once a proof is assembled, the entirety of the proof can be sent to a Clarity smart contract endpoint. This can be the clarity-bitcoin.clar contract or a custom contract the delegates to clartiy-bitcoin.clar.` 

In Getting Started:
* Add example code or remove `Example code coming soon.`
* Add code snippets from tests to show how to use stacks-bitcoin-api

In Limitations:
* The section about limitations should be updated.

In Coming soon:
* Update the section or remove it or add github issues

In Acknowledgements:
* Fix typo `Freiger` -> `Friedger`

**Comment by bgok** [comment]
> Fix typo Freiger -> Friedger
Apologies. 😊 

> The section about limitations should be updated.
As part of the updates I added a test for coinbase transactions and they can be verified. However, the coinbase message isn't available.
